---
# cp ~/ansible/prod/../docker/* /tmp/nginx-tmp
- name: Copy docker to folder
  copy:
    src: "{{ playbook_dir }}/../docker/"
    dest: "{{ docker_remote_app_dir }}"
    mode: 0755
  tags:
    - nginx-docker

# cd /tmp/nginx-tmp/ && docker-compose up -d --build
- name: Rebuild images defined in compose file and restart containers
  command: docker-compose up -d --build
  changed_when: false
  args:
    chdir: "{{ docker_remote_app_dir }}"
  tags:
    - nginx-docker
