---
# cp ~/ansible/prod/../docker/* /tmp/nginx-tmp
- name: copy_docker_to_folder
  copy:
    src: "{{ playbook_dir }}/../docker/"
    dest: "{{ docker_remote_app_dir }}"
  tags:
    - nginx-docker

# cd /tmp/nginx-tmp/ && docker-compose up -d --build
- name: rebuild_images_defined_in_compose_file_and_restart_containers
  command: docker-compose up -d --build
  changed_when: false
  args:
    chdir: "{{ docker_remote_app_dir }}"
  tags:
    - nginx-docker
